In [17]:
import tensorflow as tf
import numpy as np
import math
import matplotlib.pyplot as plt
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers

In [44]:
tf.keras.backend.clear_session()

inputs = tf.keras.Input(shape=(2,))

layer = layers.Dense(2, activation='sigmoid')
hidden = layer(inputs)

outputs = layers.Dense(2, activation = 'sigmoid')(hidden)

model = tf.keras.Model(inputs=inputs, outputs=outputs, name="HW9")
model.summary()

Model: "HW9"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 2)]               0         
                                                                 
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 2)                 6         
                                                                 
Total params: 12
Trainable params: 12
Non-trainable params: 0
_________________________________________________________________


In [45]:
model.get_weights()

[array([[ 0.11056805, -1.0056714 ],
        [ 0.05756497, -0.06084239]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.6981696 ,  0.5180447 ],
        [ 0.5896915 , -0.53648025]], dtype=float32),
 array([0., 0.], dtype=float32)]

In [46]:
x = np.array([[0.2, 0.8]])
y = np.array([[0, 1]])

In [47]:
model.compile(optimizer = tf.keras.optimizers.SGD(learning_rate = 0.4), loss = 'mse', 
              metrics = ['accuracy'])
history = model.fit(x=x, y=y, epochs = 1000, verbose = 0, batch_size = 1)

In [48]:
model.get_weights()

[array([[ 0.22259113, -1.0272397 ],
        [ 0.5056569 , -0.14712057]], dtype=float32),
 array([ 0.56011486, -0.10784769], dtype=float32),
 array([[-0.8626992 ,  1.7738122 ],
        [-0.44380265,  0.28603292]], dtype=float32),
 array([-2.7173564,  2.16547  ], dtype=float32)]

In [8]:
#import tensorflow as tf
import tensorflow.compat.v1 as tf

import numpy as np
import math
import matplotlib.pyplot as plt
import pandas as pd
from tensorflow import keras
from tensorflow.keras import layers

tf.disable_v2_behavior()

In [9]:
X = np.array([[0.2],[0.8]], dtype = np.float32)
Y = np.array([[0],[1]], dtype = np.float32)

In [10]:
w1 = tf.Variable([[0.15,0.25],[0.2,0.3]])
w2 = tf.Variable([[0.4,0.5],[0.45,0.55]])

In [11]:
hidden = tf.sigmoid(tf.matmul(w1,X)+[[0.2,0.2]])
output = tf.sigmoid(tf.matmul(w2,hidden)+[[0.5,0.5]])

loss = tf.reduce_mean(tf.square(output-Y))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.4)

train = optimizer.minimize(loss)

In [14]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(100000):
        if step in [0,1,2] :
            sess.run(train)
            print(sess.run(loss))
            print(sess.run([w1,w2]))
            print(sess.run(output))
            print(' ')

0.29839587
[array([[0.14930938, 0.24723752],
       [0.19913545, 0.29654178]], dtype=float32), array([[0.3655354 , 0.46485993],
       [0.46116534, 0.5613842 ]], dtype=float32)]
[[0.73264945 0.73264945]
 [0.75501734 0.75501734]]
 
0.29157138
[array([[0.14870618, 0.24482474],
       [0.19835524, 0.29342094]], dtype=float32), array([[0.33078873, 0.4294393 ],
       [0.47213688, 0.57256854]], dtype=float32)]
[[0.7240791  0.7240791 ]
 [0.75740516 0.75740516]]
 
0.28469175
[array([[0.1481936 , 0.24277441],
       [0.1976629 , 0.2906516 ]], dtype=float32), array([[0.2957906 , 0.39376974],
       [0.48292089, 0.5835594 ]], dtype=float32)]
[[0.71530455 0.71530455]
 [0.75974405 0.75974405]]
 
