### 2.	Classify the MNIST data with SVM (linear, poly, and rbs kernels), KNN, DT, and RF. Summarize their accuracy in a table and put confusion matrixes in the MS word file. 

MNIST datasets are composed of two datasets: mnist_train.csv and mnist_test.csv. Train dataset has 60,000 samples and test data 10,000 samples. The first column is the label and the remaining columns of 784 are features with the maximum value of 256. If accuracy rate is not high, you better to scale all features by dividing them by 256. 60,000 samples are too big so use first 10% of datasets.

In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

In [24]:
mnist_test = pd.read_csv(r'C:\Users\Yunseok Choi\Google 드라이브\기술경영대학원\3학기\인공지능\Assignment#5\mnist_test.csv', header=None)
mnist_train = pd.read_csv(r'C:\Users\Yunseok Choi\Google 드라이브\기술경영대학원\3학기\인공지능\Assignment#5\mnist_train.csv', header=None)
mnist_train = mnist_train.iloc[:6000]
mnist_test = mnist_test.iloc[:1000]

In [25]:
x_train = mnist_train[mnist_train.columns[1:]]
y_train = mnist_train[[0]].values.ravel()
x_test = mnist_test[mnist_test.columns[1:]]
y_test = mnist_test[[0]].values.ravel()

## Before Normalization

In [26]:
svm_linear = svm.SVC(kernel = 'linear', gamma = 0.01)
svm_linear.fit(x_train,y_train)
svm_linear_trainscore = metrics.accuracy_score(y_train, svm_linear.predict(x_train))
svm_linear_testscore = metrics.accuracy_score(y_test, svm_linear.predict(x_test))
confusion_linear_train = metrics.confusion_matrix(y_train, svm_linear.predict(x_train))
confusion_linear_test = metrics.confusion_matrix(y_test, svm_linear.predict(x_test))

print('Accuracy rate of svm_linear trainset = {}'.format(svm_linear_trainscore))
print('Accuracy rate of svm_linear testset = {}'.format(svm_linear_testscore))
print(' ')
print('Confusion matrix of svm_lienar_train')
print(confusion_linear_train)
print('Confusion matrix of svm_lienar_test')
print(confusion_linear_test)

Accuracy rate of svm_linear trainset = 1.0
Accuracy rate of svm_linear testset = 0.888
 
Confusion matrix of svm_lienar_train
[[592   0   0   0   0   0   0   0   0   0]
 [  0 671   0   0   0   0   0   0   0   0]
 [  0   0 581   0   0   0   0   0   0   0]
 [  0   0   0 608   0   0   0   0   0   0]
 [  0   0   0   0 623   0   0   0   0   0]
 [  0   0   0   0   0 514   0   0   0   0]
 [  0   0   0   0   0   0 608   0   0   0]
 [  0   0   0   0   0   0   0 651   0   0]
 [  0   0   0   0   0   0   0   0 551   0]
 [  0   0   0   0   0   0   0   0   0 601]]
Confusion matrix of svm_lienar_test
[[ 80   0   0   0   0   2   2   0   0   1]
 [  0 125   0   0   0   0   1   0   0   0]
 [  2   2  98   1   1   0   2   3   5   2]
 [  1   0   2  93   0   6   1   1   2   1]
 [  0   1   0   0 102   0   1   0   0   6]
 [  1   1   0   2   0  75   1   0   5   2]
 [  3   0   3   0   2   0  79   0   0   0]
 [  0   1   5   1   2   0   0  85   0   5]
 [  2   0   1   4   2   3   0   2  74   1]
 [  0   1   0   3   

In [27]:
svm_poly = svm.SVC(kernel = 'poly', gamma = 0.01)
svm_poly.fit(x_train,y_train)
svm_poly_trainscore = metrics.accuracy_score(y_train, svm_poly.predict(x_train))
svm_poly_testscore = metrics.accuracy_score(y_test, svm_poly.predict(x_test))
confusion_poly_train = metrics.confusion_matrix(y_train, svm_poly.predict(x_train))
confusion_poly_test = metrics.confusion_matrix(y_test, svm_poly.predict(x_test))
print('Accuracy rate of svm_poly trainset = {}'.format(svm_poly_trainscore))
print('Accuracy rate of svm_poly testset = {}'.format(svm_poly_testscore))
print(' ')
print('Confusion matrix of svm_poly_train')
print(confusion_poly_train)
print('Confusion matrix of svm_poly_test')
print(confusion_poly_test)

Accuracy rate of svm_poly trainset = 1.0
Accuracy rate of svm_poly testset = 0.927
 
Confusion matrix of svm_poly_train
[[592   0   0   0   0   0   0   0   0   0]
 [  0 671   0   0   0   0   0   0   0   0]
 [  0   0 581   0   0   0   0   0   0   0]
 [  0   0   0 608   0   0   0   0   0   0]
 [  0   0   0   0 623   0   0   0   0   0]
 [  0   0   0   0   0 514   0   0   0   0]
 [  0   0   0   0   0   0 608   0   0   0]
 [  0   0   0   0   0   0   0 651   0   0]
 [  0   0   0   0   0   0   0   0 551   0]
 [  0   0   0   0   0   0   0   0   0 601]]
Confusion matrix of svm_poly_test
[[ 82   0   0   0   0   2   1   0   0   0]
 [  0 124   0   0   0   0   1   0   1   0]
 [  3   3 102   2   0   0   1   3   2   0]
 [  0   3   1  92   0   7   1   1   1   1]
 [  0   0   0   0 106   0   1   1   0   2]
 [  1   0   0   1   1  81   1   0   1   1]
 [  1   0   0   0   2   1  83   0   0   0]
 [  0   3   4   0   2   0   0  89   0   1]
 [  2   0   1   4   2   0   0   0  79   1]
 [  0   0   0   0   3   0   

In [28]:
svm_rbf = svm.SVC(kernel = 'rbf', gamma = 0.01)
svm_rbf.fit(x_train,y_train)
svm_rbf_trainscore = metrics.accuracy_score(y_train, svm_rbf.predict(x_train))
svm_rbf_testscore = metrics.accuracy_score(y_test, svm_rbf.predict(x_test))
confusion_rbf_train = metrics.confusion_matrix(y_train, svm_rbf.predict(x_train))
confusion_rbf_test = metrics.confusion_matrix(y_test, svm_rbf.predict(x_test))
print('Accuracy rate of svm_rbf trainset = {}'.format(svm_rbf_trainscore))
print('Accuracy rate of svm_rbf testset = {}'.format(svm_rbf_testscore))
print(' ')
print('Confusion matrix of svm_rbf_train')
print(confusion_rbf_train)
print('Confusion matrix of svm_rbf_test')
print(confusion_rbf_test)

Accuracy rate of svm_rbf trainset = 1.0
Accuracy rate of svm_rbf testset = 0.126
 
Confusion matrix of svm_rbf_train
[[592   0   0   0   0   0   0   0   0   0]
 [  0 671   0   0   0   0   0   0   0   0]
 [  0   0 581   0   0   0   0   0   0   0]
 [  0   0   0 608   0   0   0   0   0   0]
 [  0   0   0   0 623   0   0   0   0   0]
 [  0   0   0   0   0 514   0   0   0   0]
 [  0   0   0   0   0   0 608   0   0   0]
 [  0   0   0   0   0   0   0 651   0   0]
 [  0   0   0   0   0   0   0   0 551   0]
 [  0   0   0   0   0   0   0   0   0 601]]
Confusion matrix of svm_rbf_test
[[  0  85   0   0   0   0   0   0   0   0]
 [  0 126   0   0   0   0   0   0   0   0]
 [  0 116   0   0   0   0   0   0   0   0]
 [  0 107   0   0   0   0   0   0   0   0]
 [  0 110   0   0   0   0   0   0   0   0]
 [  0  87   0   0   0   0   0   0   0   0]
 [  0  87   0   0   0   0   0   0   0   0]
 [  0  99   0   0   0   0   0   0   0   0]
 [  0  89   0   0   0   0   0   0   0   0]
 [  0  94   0   0   0   0   0   

In [33]:
knn = KNeighborsClassifier(n_neighbors = 3).fit(x_train,y_train)
knn_score_train = metrics.accuracy_score(y_train, knn.predict(x_train))
knn_score_test = metrics.accuracy_score(y_test, knn.predict(x_test))
print('Accuracy rate of knn trainset = {}'.format(knn_score_train))
print('Accuracy rate of knn testset= {}'.format(knn_score_test))

confusion_knn_train = metrics.confusion_matrix(y_train, knn.predict(x_train))
confusion_knn_test = metrics.confusion_matrix(y_test, knn.predict(x_test))
print('Confusion matrix of knn_train')
print(confusion_knn_train)
print('Confusion matrix of knn_test')
print(confusion_knn_test)

Accuracy rate of knn trainset = 0.9713333333333334
Accuracy rate of knn testset= 0.913
Confusion matrix of knn_train
[[590   1   0   1   0   0   0   0   0   0]
 [  0 668   0   0   1   0   0   1   0   1]
 [  0  10 563   0   0   0   1   7   0   0]
 [  2   2   3 589   0   5   2   4   1   0]
 [  0   9   0   0 602   0   1   0   0  11]
 [  1   2   1   4   3 496   4   0   1   2]
 [  3   3   0   0   0   1 601   0   0   0]
 [  1  10   0   0   0   0   0 634   0   6]
 [  3  10   4   6   4   5   2   2 511   4]
 [  7   3   1   4   5   0   0   7   0 574]]
Confusion matrix of knn_test
[[ 85   0   0   0   0   0   0   0   0   0]
 [  0 126   0   0   0   0   0   0   0   0]
 [  3   5  97   0   1   0   2   6   2   0]
 [  0   2   0  95   0   2   2   2   2   2]
 [  0   2   0   0  99   0   1   1   0   7]
 [  0   1   0   2   1  81   0   0   1   1]
 [  2   0   0   0   1   0  84   0   0   0]
 [  0   5   0   0   1   1   0  91   0   1]
 [  4   2   3   4   1   2   1   0  68   4]
 [  0   0   0   1   4   0   0   2   

In [14]:
DT = tree.DecisionTreeClassifier().fit(x_train, y_train)
DT_score_train = metrics.accuracy_score(y_train, DT.predict(x_train))
DT_score_test = metrics.accuracy_score(y_test, DT.predict(x_test))
print('Accuracy rate of DT trainset= {}'.format(DT_score_train))
print('Accuracy rate of DT testset= {}'.format(DT_score_test))
print(' ')

DT_confusion_train = metrics.confusion_matrix(y_train, DT.predict(x_train))
DT_confusion_test = metrics.confusion_matrix(y_test, DT.predict(x_test))
print('Confusion matrix of DT_train')
print(DT_confusion_train)
print('Confusion matrix of DT_test')
print(DT_confusion_test)
print(' ')

Accuracy rate of DT trainset= 1.0
Accuracy rate of DT testset= 0.759
 
Confusion matrix of DT_train
[[592   0   0   0   0   0   0   0   0   0]
 [  0 671   0   0   0   0   0   0   0   0]
 [  0   0 581   0   0   0   0   0   0   0]
 [  0   0   0 608   0   0   0   0   0   0]
 [  0   0   0   0 623   0   0   0   0   0]
 [  0   0   0   0   0 514   0   0   0   0]
 [  0   0   0   0   0   0 608   0   0   0]
 [  0   0   0   0   0   0   0 651   0   0]
 [  0   0   0   0   0   0   0   0 551   0]
 [  0   0   0   0   0   0   0   0   0 601]]
Confusion matrix of DT_test
[[ 75   1   0   1   2   3   1   2   0   0]
 [  0 113   2   5   0   1   0   2   3   0]
 [  5   5  85   4   1   2   4   2   8   0]
 [  1   3   1  67   1  13   4   6   6   5]
 [  1   1   6   1  84   3   1   5   4   4]
 [  2   1   1   7   4  53   3   7   4   5]
 [  4   0   1   1   0   4  70   2   3   2]
 [  1   2   3   2   1   2   1  78   0   9]
 [  2   0   7   1   4   4   0   2  65   4]
 [  0   0   2   1   3   4   2   8   5  69]]
 


In [15]:
RFC = RandomForestClassifier().fit(x_train, y_train)
RFC_score_train = metrics.accuracy_score(y_train, RFC.predict(x_train))
RFC_score_test = metrics.accuracy_score(y_test, RFC.predict(x_test))
print('Accuracy rate of RFC trainset= {}'.format(RFC_score_train))
print('Accuracy rate of RFC testset= {}'.format(RFC_score_test))
print(' ')
RFC_confusion_train = metrics.confusion_matrix(y_train, RFC.predict(x_train))
RFC_confusion_test = metrics.confusion_matrix(y_test, RFC.predict(x_test))
print('Confusion matrix of RFC_train')
print(RFC_confusion_train)
print('Confusion matrix of RFC_test')
print(RFC_confusion_test)
print(' ')

Accuracy rate of RFC trainset= 1.0
Accuracy rate of RFC testset= 0.93
 
Confusion matrix of RFC_train
[[592   0   0   0   0   0   0   0   0   0]
 [  0 671   0   0   0   0   0   0   0   0]
 [  0   0 581   0   0   0   0   0   0   0]
 [  0   0   0 608   0   0   0   0   0   0]
 [  0   0   0   0 623   0   0   0   0   0]
 [  0   0   0   0   0 514   0   0   0   0]
 [  0   0   0   0   0   0 608   0   0   0]
 [  0   0   0   0   0   0   0 651   0   0]
 [  0   0   0   0   0   0   0   0 551   0]
 [  0   0   0   0   0   0   0   0   0 601]]
Confusion matrix of RFC_test
[[ 84   0   0   0   0   0   1   0   0   0]
 [  0 125   0   1   0   0   0   0   0   0]
 [  0   0 108   1   0   0   1   4   2   0]
 [  0   0   1  94   0   6   1   3   0   2]
 [  0   0   0   0 100   1   3   0   1   5]
 [  1   0   0   2   1  82   0   0   1   0]
 [  3   0   0   0   1   1  82   0   0   0]
 [  0   1   4   0   1   0   0  93   0   0]
 [  0   0   4   2   2   1   2   0  75   3]
 [  0   1   0   1   2   0   0   1   2  87]]
 


## After Normalization

In [34]:
x_train = mnist_train[mnist_train.columns[1:]].applymap(lambda x: x/265)
y_train = mnist_train[[0]].values.ravel()
x_test = mnist_test[mnist_test.columns[1:]].applymap(lambda x: x/265)
y_test = mnist_test[[0]].values.ravel()

In [20]:
svm_linear = svm.SVC(kernel = 'linear', gamma = 0.01)
svm_linear.fit(x_train,y_train)
svm_linear_trainscore = metrics.accuracy_score(y_train, svm_linear.predict(x_train))
svm_linear_testscore = metrics.accuracy_score(y_test, svm_linear.predict(x_test))
confusion_linear_train = metrics.confusion_matrix(y_train, svm_linear.predict(x_train))
confusion_linear_test = metrics.confusion_matrix(y_test, svm_linear.predict(x_test))

print('Accuracy rate of svm_linear trainset = {}'.format(svm_linear_trainscore))
print('Accuracy rate of svm_linear testset = {}'.format(svm_linear_testscore))
print(' ')
print('Confusion matrix of svm_lienar_train')
print(confusion_linear_train)
print('Confusion matrix of svm_lienar_test')
print(confusion_linear_test)

Accuracy rate of svm_linear trainset = 0.9991666666666666
Accuracy rate of svm_linear testset = 0.897
 
Confusion matrix of svm_lienar_train
[[592   0   0   0   0   0   0   0   0   0]
 [  0 671   0   0   0   0   0   0   0   0]
 [  0   0 581   0   0   0   0   0   0   0]
 [  0   0   0 608   0   0   0   0   0   0]
 [  0   0   0   0 622   0   0   0   0   1]
 [  0   0   0   0   0 514   0   0   0   0]
 [  0   0   0   0   0   0 608   0   0   0]
 [  0   1   1   0   0   0   0 649   0   0]
 [  0   0   0   0   0   0   0   0 551   0]
 [  0   0   0   0   0   0   0   2   0 599]]
Confusion matrix of svm_lienar_test
[[ 80   0   0   0   0   2   2   0   0   1]
 [  0 125   0   0   0   0   1   0   0   0]
 [  2   2  98   1   1   0   2   3   5   2]
 [  1   0   2  94   0   5   1   1   2   1]
 [  0   1   0   0 103   0   1   0   0   5]
 [  1   1   0   2   0  75   1   0   5   2]
 [  3   0   3   0   2   0  79   0   0   0]
 [  0   1   4   1   2   0   0  88   0   3]
 [  2   0   1   4   2   3   0   2  74   1]
 [  0

In [37]:
svm_poly = svm.SVC(kernel = 'poly', gamma = 0.01)
svm_poly.fit(x_train,y_train)
predict_train = svm_poly.predict(x_train)
predict_test = svm_poly.predict(x_test)
svm_poly_trainscore = metrics.accuracy_score(y_train, predict_train)
svm_poly_testscore = metrics.accuracy_score(y_test, predict_test)
confusion_poly_train = metrics.confusion_matrix(y_train, predict_train)
confusion_poly_test = metrics.confusion_matrix(y_test, predict_test)
print('Accuracy rate of svm_poly trainset = {}'.format(svm_poly_trainscore))
print('Accuracy rate of svm_poly testset = {}'.format(svm_poly_testscore))
print(' ')
print('Confusion matrix of svm_poly_train')
print(confusion_poly_train)
print('Confusion matrix of svm_poly_test')
print(confusion_poly_test)

Accuracy rate of svm_poly trainset = 0.959
Accuracy rate of svm_poly testset = 0.904
 
Confusion matrix of svm_poly_train
[[572   4   0   2   1   9   2   1   1   0]
 [  0 664   2   1   1   0   0   1   0   2]
 [  1  22 540   0   8   1   0   4   4   1]
 [  0  16   0 571   2  11   0   6   1   1]
 [  0   9   0   0 610   0   0   0   0   4]
 [  0  10   1   1   0 499   2   0   1   0]
 [  1  13   0   0   0   3 590   0   1   0]
 [  0  18   1   0   6   0   0 621   0   5]
 [  0  14   0   2   4   5   2   1 522   1]
 [  1   8   0   4  12   2   0   7   2 565]]
Confusion matrix of svm_poly_test
[[ 80   0   0   0   1   3   1   0   0   0]
 [  0 124   0   0   0   0   1   0   1   0]
 [  1   9  96   1   0   0   1   4   3   1]
 [  0   3   0  92   0   8   1   2   0   1]
 [  0   4   1   0 101   0   0   0   0   4]
 [  1   1   0   1   1  80   1   0   1   1]
 [  2   1   0   0   1   0  83   0   0   0]
 [  0   4   2   1   2   0   0  89   0   1]
 [  1   2   1   2   2   2   0   1  77   1]
 [  0   1   0   0   6   1 

In [16]:
svm_rbf = svm.SVC(kernel = 'rbf', gamma = 0.01)
svm_rbf.fit(x_train,y_train)
svm_rbf_trainscore = metrics.accuracy_score(y_train, svm_rbf.predict(x_train))
svm_rbf_testscore = metrics.accuracy_score(y_test, svm_rbf.predict(x_test))
confusion_rbf_train = metrics.confusion_matrix(y_train, svm_rbf.predict(x_train))
confusion_rbf_test = metrics.confusion_matrix(y_test, svm_rbf.predict(x_test))
print('Accuracy rate of svm_rbf trainset = {}'.format(svm_rbf_trainscore))
print('Accuracy rate of svm_rbf testset = {}'.format(svm_rbf_testscore))
print(' ')
print('Confusion matrix of svm_rbf_train')
print(confusion_rbf_train)
print('Confusion matrix of svm_rbf_test')
print(confusion_rbf_test)

Accuracy rate of svm_rbf trainset = 0.9775
Accuracy rate of svm_rbf testset = 0.928
 
Confusion matrix of svm_rbf_train
[[589   0   0   0   2   0   0   0   1   0]
 [  0 664   3   2   1   0   0   0   0   1]
 [  1   1 565   1   6   1   0   2   4   0]
 [  1   3   1 588   1   5   1   5   2   1]
 [  0   1   0   0 613   0   1   0   0   8]
 [  0   2   2   3   1 500   5   0   0   1]
 [  2   1   0   0   0   3 601   0   1   0]
 [  0   3   3   0   5   0   0 633   0   7]
 [  0   2   1   1   1   3   4   1 537   1]
 [  3   3   0   4   5   1   0   8   2 575]]
Confusion matrix of svm_rbf_test
[[ 83   0   0   0   0   1   1   0   0   0]
 [  0 124   1   0   0   0   0   0   1   0]
 [  1   0 104   1   1   0   1   3   4   1]
 [  0   0   0  94   0   8   1   1   2   1]
 [  0   0   1   0 103   0   0   1   0   5]
 [  1   0   0   3   0  80   1   0   1   1]
 [  3   0   1   0   1   0  82   0   0   0]
 [  0   2   3   0   1   0   0  93   0   0]
 [  2   0   1   3   2   0   0   1  80   0]
 [  0   0   0   1   2   0   0

In [35]:
knn = KNeighborsClassifier(n_neighbors = 3).fit(x_train,y_train)
knn_score_train = metrics.accuracy_score(y_train, knn.predict(x_train))
knn_score_test = metrics.accuracy_score(y_test, knn.predict(x_test))
print('Accuracy rate of knn trainset = {}'.format(knn_score_train))
print('Accuracy rate of knn testset= {}'.format(knn_score_test))

confusion_knn_train = metrics.confusion_matrix(y_train, knn.predict(x_train))
confusion_knn_test = metrics.confusion_matrix(y_test, knn.predict(x_test))
print('Confusion matrix of knn_train')
print(confusion_knn_train)
print('Confusion matrix of knn_test')
print(confusion_knn_test)

Accuracy rate of knn trainset = 0.9713333333333334
Accuracy rate of knn testset= 0.913
Confusion matrix of knn_train
[[590   1   0   1   0   0   0   0   0   0]
 [  0 668   0   0   1   0   0   1   0   1]
 [  0  10 563   0   0   0   1   7   0   0]
 [  2   2   3 589   0   5   2   4   1   0]
 [  0   9   0   0 602   0   1   0   0  11]
 [  1   2   1   4   3 496   4   0   1   2]
 [  3   3   0   0   0   1 601   0   0   0]
 [  1  10   0   0   0   0   0 634   0   6]
 [  3  10   4   6   4   5   2   2 511   4]
 [  7   3   1   4   5   0   0   7   0 574]]
Confusion matrix of knn_test
[[ 85   0   0   0   0   0   0   0   0   0]
 [  0 126   0   0   0   0   0   0   0   0]
 [  3   5  97   0   1   0   2   6   2   0]
 [  0   2   0  95   0   2   2   2   2   2]
 [  0   2   0   0  99   0   1   1   0   7]
 [  0   1   0   2   1  81   0   0   1   1]
 [  2   0   0   0   1   0  84   0   0   0]
 [  0   5   0   0   1   1   0  91   0   1]
 [  4   2   3   4   1   2   1   0  68   4]
 [  0   0   0   1   4   0   0   2   

In [36]:
DT = tree.DecisionTreeClassifier().fit(x_train, y_train)
DT_score_train = metrics.accuracy_score(y_train, DT.predict(x_train))
DT_score_test = metrics.accuracy_score(y_test, DT.predict(x_test))
print('Accuracy rate of DT trainset= {}'.format(DT_score_train))
print('Accuracy rate of DT testset= {}'.format(DT_score_test))
print(' ')

DT_confusion_train = metrics.confusion_matrix(y_train, DT.predict(x_train))
DT_confusion_test = metrics.confusion_matrix(y_test, DT.predict(x_test))
print('Confusion matrix of DT_train')
print(DT_confusion_train)
print('Confusion matrix of DT_test')
print(DT_confusion_test)
print(' ')

Accuracy rate of DT trainset= 1.0
Accuracy rate of DT testset= 0.766
 
Confusion matrix of DT_train
[[592   0   0   0   0   0   0   0   0   0]
 [  0 671   0   0   0   0   0   0   0   0]
 [  0   0 581   0   0   0   0   0   0   0]
 [  0   0   0 608   0   0   0   0   0   0]
 [  0   0   0   0 623   0   0   0   0   0]
 [  0   0   0   0   0 514   0   0   0   0]
 [  0   0   0   0   0   0 608   0   0   0]
 [  0   0   0   0   0   0   0 651   0   0]
 [  0   0   0   0   0   0   0   0 551   0]
 [  0   0   0   0   0   0   0   0   0 601]]
Confusion matrix of DT_test
[[ 74   0   1   2   1   1   2   1   1   2]
 [  0 113   0   5   3   0   2   1   2   0]
 [  4   3  82   3   1   3   3   7   7   3]
 [  3   5   3  67   1   9   5   5   5   4]
 [  1   2   1   1  89   5   3   2   2   4]
 [  1   0   4   5   1  62   3   4   4   3]
 [  4   0   2   0   4   4  68   1   4   0]
 [  1   1   1   3   1   2   0  78   1  11]
 [  1   2   5   5   4   4   2   1  63   2]
 [  1   0   1   2   4   1   1   9   5  70]]
 


In [38]:
RFC = RandomForestClassifier().fit(x_train, y_train)
RFC_score_train = metrics.accuracy_score(y_train, RFC.predict(x_train))
RFC_score_test = metrics.accuracy_score(y_test, RFC.predict(x_test))
print('Accuracy rate of RFC trainset= {}'.format(RFC_score_train))
print('Accuracy rate of RFC testset= {}'.format(RFC_score_test))
print(' ')
RFC_confusion_train = metrics.confusion_matrix(y_train, RFC.predict(x_train))
RFC_confusion_test = metrics.confusion_matrix(y_test, RFC.predict(x_test))
print('Confusion matrix of RFC_train')
print(RFC_confusion_train)
print('Confusion matrix of RFC_test')
print(RFC_confusion_test)
print(' ')

Accuracy rate of RFC trainset= 1.0
Accuracy rate of RFC testset= 0.927
 
Confusion matrix of RFC_train
[[592   0   0   0   0   0   0   0   0   0]
 [  0 671   0   0   0   0   0   0   0   0]
 [  0   0 581   0   0   0   0   0   0   0]
 [  0   0   0 608   0   0   0   0   0   0]
 [  0   0   0   0 623   0   0   0   0   0]
 [  0   0   0   0   0 514   0   0   0   0]
 [  0   0   0   0   0   0 608   0   0   0]
 [  0   0   0   0   0   0   0 651   0   0]
 [  0   0   0   0   0   0   0   0 551   0]
 [  0   0   0   0   0   0   0   0   0 601]]
Confusion matrix of RFC_test
[[ 84   0   0   0   0   0   1   0   0   0]
 [  0 124   0   1   0   0   0   0   1   0]
 [  0   0 105   2   1   0   1   3   4   0]
 [  0   0   0  96   0   6   1   2   0   2]
 [  1   0   1   1 100   0   1   1   0   5]
 [  1   0   0   1   1  82   0   0   1   1]
 [  3   0   0   0   1   1  82   0   0   0]
 [  0   0   4   0   2   0   0  90   0   3]
 [  0   0   3   2   2   2   1   0  75   4]
 [  0   1   0   1   0   0   0   1   2  89]]
 
